# Configure Atom preferences
---
- hosts: all

  tasks:
  - name: Check if Atom installed
    stat: path="/Users/{{ ansible_user_id }}/.atom"
    register: check_atom_config_path

  - name: Configure Atom
    copy:
      src: ./files/.atom/config.cson
      dest: "/Users/{{ ansible_user_id }}/.atom/config.cson"
      owner: {{ ansible_user_id }}
      group: staff
      mode: 0644
    when: check_atom_config_path.stat.exists
