# Configure the command line
---
- hosts: all

  - name: Copy git prompt
    copy:
      src: ./files/.prompt
      dest: "/Users/{{ ansible_user_id }}/.prompt"
      owner: {{ ansible_user_id }}
      group: staff
      mode: 0644

  - name: Copy bash_profile
    copy:
      src: ./files/.bash_profile
      dest: "/Users/{{ ansible_user_id }}/.bash_profile"
      owner: {{ ansible_user_id }}
      group: staff
      mode: 0644
