# Configure a workstation
---
- include: local_installs.yaml
- include: cli_config.yaml
- include: munki_config.yaml
- include: atom_config.yaml

- hosts: 127.0.0.1
  connection: local
  vars:
    atom_packages_packages:
      git-plus
  roles:
    - hnakamur.atom-packages
